### ISSUE TITLE
Error when moving to directory greater than 2 folders deep

### ISSUE THREAD

**Issue by NateMietk** [rorynolan/filesstrings#6]
Hi - first, love the package! I was hoping to move some files into a fairly deep directory but it does not recognize folders that are 3 deep.  What I mean by this is:

```library(filesstrings)

# Create file
file.create("test.txt")

# Create directory
dir.create("MyDir")
dir.create(file.path("MyDir", "Dir1"))
dir.create(file.path("MyDir", "Dir1", "Dir2"))

# Move new file to new directory
file.move("test.txt", "MyDir")

file_list <- list.files('MyDir', full.names=TRUE)

file.move(file_list, file.path("MyDir", "Dir1", "Dir2"))

Error in file.move(file_list, file.path("MyDir", "Dir1", "Dir2")) : 
  Assertion on 'files' failed: File expected, but directory in place: 'MyDir/Dir1'.
```

Any explanation on why this is happening?  I would have assumed the location of the directory would be insignificant as long as the path is valid. Thanks!

**Comment by rorynolan** [comment]
Hi Nate. Thanks for the love!
The problem here is that `file_list <- list.files('MyDir', full.names=TRUE)` returns `file_list` as `c("MyDir/Dir1", "MyDir/test.txt")`, i.e. there's a directory `MyDir/Dir1` in `file_list` and then in the `file.move()` call, you attempt to move that directory `MyDir/Dir1` to a subdirectory of itself `MyDir/Dir1/Dir2`, which doesn't really make sense. I guess you really just want to list files and not directories. For this use `file_list <- fs::dir_ls("myDir", type = "file")`. 
In general, this `fs` package is great for file manipulation. I wrote `filesstrings` before `fs` was written, but then `fs` came along as a more comprehensive suite, so check it out. But feel free to keep using `filesstrings` too!

**Comment by rorynolan** [comment]
Closing this now. If you have further questions, feel free to comment and reopen. 
Thanks for reaching out :-)
